### ISSUE TITLE
No luck in making it work

### ISSUE THREAD

**Issue by syam-prasad** [x2es/boilerplate-karma-mocha-chai-requirejs#6]
I have the nodejs v4.1.1 and npm - 2.14.4

karma start is giving me the below error. 

04 10 2015 12:26:02.201:WARN [reporter]: Can not load "mp3", it is not registered!
  Perhaps you are missing some plugin?
04 10 2015 12:26:02.204:WARN [reporter]: Can not load "html", it is not registered!
  Perhaps you are missing some plugin?
/Users/sprasad2/npme/lib/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:mocha"! (Resolving: framework:mocha)
    at error (/Users/sprasad2/npme/lib/node_modules/karma/node_modules/di/lib/injector.js:22:12)
    at Object.parent.get (/Users/sprasad2/npme/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/Users/sprasad2/npme/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /Users/sprasad2/npme/lib/node_modules/karma/lib/server.js:137:20
    at Array.forEach (native)
    at Server._start (/Users/sprasad2/npme/lib/node_modules/karma/lib/server.js:136:21)
    at invoke (/Users/sprasad2/npme/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/sprasad2/npme/lib/node_modules/karma/lib/server.js:101:18)
    at Object.exports.run (/Users/sprasad2/npme/lib/node_modules/karma/lib/cli.js:231:26)
    at Object.<anonymous> (/Users/sprasad2/npme/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)

This is the output of npm list (sorry for the long lengthy text. Couldn't upload it as text file.)

boilerplate-karma-mocha-chai-requirejs@0.1.2 /Users/sprasad2/SR_CQ_Workspace/CMT/widgets/dev/widgets/wwsui/v3
├─┬ chai@3.3.0
│ ├── assertion-error@1.0.1
│ ├─┬ deep-eql@0.1.3
│ │ └── type-detect@0.1.1
│ └── type-detect@1.0.0
├─┬ karma@0.13.10
│ ├── bluebird@2.10.2
│ ├─┬ body-parser@1.14.1
│ │ ├── bytes@2.1.0
│ │ ├── content-type@1.0.1
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── depd@1.1.0
│ │ ├─┬ http-errors@1.3.1
│ │ │ ├── inherits@2.0.1
│ │ │ └── statuses@1.2.1
│ │ ├── iconv-lite@0.4.12
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ ├── qs@5.1.0
│ │ ├─┬ raw-body@2.1.4
│ │ │ └── unpipe@1.0.0
│ │ └─┬ type-is@1.6.9
│ │   ├── media-typer@0.3.0
│ │   └─┬ mime-types@2.1.7
│ │     └── mime-db@1.19.0
│ ├─┬ chokidar@1.2.0
│ │ ├─┬ anymatch@1.3.0
│ │ │ └─┬ micromatch@2.2.0
│ │ │   ├─┬ arr-diff@1.1.0
│ │ │   │ ├── arr-flatten@1.0.1
│ │ │   │ └── array-slice@0.2.3
│ │ │   ├── array-unique@0.2.1
│ │ │   ├─┬ braces@1.8.1
│ │ │   │ ├─┬ expand-range@1.8.1
│ │ │   │ │ └─┬ fill-range@2.2.2
│ │ │   │ │   ├── is-number@1.1.2
│ │ │   │ │   ├── isobject@1.0.2
│ │ │   │ │   ├── randomatic@1.1.0
│ │ │   │ │   └── repeat-string@1.5.2
│ │ │   │ ├── lazy-cache@0.2.3
│ │ │   │ ├── preserve@0.2.0
│ │ │   │ └── repeat-element@1.1.2
│ │ │   ├── expand-brackets@0.1.4
│ │ │   ├─┬ extglob@0.3.1
│ │ │   │ ├─┬ ansi-green@0.1.1
│ │ │   │ │ └── ansi-wrap@0.1.0
│ │ │   │ ├── is-extglob@1.0.0
│ │ │   │ └── success-symbol@0.1.0
│ │ │   ├── filename-regex@2.0.0
│ │ │   ├── is-glob@1.1.3
│ │ │   ├── kind-of@1.1.0
│ │ │   ├─┬ object.omit@1.1.0
│ │ │   │ ├─┬ for-own@0.1.3
│ │ │   │ │ └── for-in@0.1.4
│ │ │   │ └── isobject@1.0.2
│ │ │   ├─┬ parse-glob@3.0.4
│ │ │   │ ├── glob-base@0.3.0
│ │ │   │ ├── is-dotfile@1.0.1
│ │ │   │ ├── is-extglob@1.0.0
│ │ │   │ └── is-glob@2.0.1
│ │ │   └─┬ regex-cache@0.4.2
│ │ │     ├── is-equal-shallow@0.1.3
│ │ │     └── is-primitive@2.0.0
│ │ ├── arrify@1.0.0
│ │ ├── async-each@0.1.6
│ │ ├─┬ fsevents@1.0.1
│ │ │ ├── nan@2.0.9
│ │ │ └─┬ node-pre-gyp@0.6.11
│ │ │   ├─┬ mkdirp@0.5.1
│ │ │   │ └── minimist@0.0.8
│ │ │   ├─┬ nopt@3.0.4
│ │ │   │ └── abbrev@1.0.7
│ │ │   ├─┬ npmlog@1.2.1
│ │ │   │ ├── ansi@0.3.0
│ │ │   │ ├─┬ are-we-there-yet@1.0.4
│ │ │   │ │ ├── delegates@0.1.0
│ │ │   │ │ └─┬ readable-stream@1.1.13
│ │ │   │ │   ├── core-util-is@1.0.1
│ │ │   │ │   ├── inherits@2.0.1
│ │ │   │ │   ├── isarray@0.0.1
│ │ │   │ │   └── string_decoder@0.10.31
│ │ │   │ └─┬ gauge@1.2.2
│ │ │   │   ├── has-unicode@1.0.0
│ │ │   │   ├─┬ lodash.pad@3.1.1
│ │ │   │   │ ├── lodash._basetostring@3.0.1
│ │ │   │   │ └─┬ lodash._createpadding@3.6.1
│ │ │   │   │   └── lodash.repeat@3.0.1
│ │ │   │   ├─┬ lodash.padleft@3.1.1
│ │ │   │   │ ├── lodash._basetostring@3.0.1
│ │ │   │   │ └─┬ lodash._createpadding@3.6.1
│ │ │   │   │   └── lodash.repeat@3.0.1
│ │ │   │   └─┬ lodash.padright@3.1.1
│ │ │   │     ├── lodash._basetostring@3.0.1
│ │ │   │     └─┬ lodash._createpadding@3.6.1
│ │ │   │       └── lodash.repeat@3.0.1
│ │ │   ├─┬ rc@1.1.1
│ │ │   │ ├── deep-extend@0.2.11
│ │ │   │ ├── ini@1.3.4
│ │ │   │ ├── minimist@1.2.0
│ │ │   │ └── strip-json-comments@0.1.3
│ │ │   ├─┬ request@2.63.0
│ │ │   │ ├── aws-sign2@0.5.0
│ │ │   │ ├─┬ bl@1.0.0
│ │ │   │ │ └─┬ readable-stream@2.0.2
│ │ │   │ │   ├── core-util-is@1.0.1
│ │ │   │ │   ├── inherits@2.0.1
│ │ │   │ │   ├── isarray@0.0.1
│ │ │   │ │   ├── process-nextick-args@1.0.3
│ │ │   │ │   ├── string_decoder@0.10.31
│ │ │   │ │   └── util-deprecate@1.0.1
│ │ │   │ ├── caseless@0.11.0
│ │ │   │ ├─┬ combined-stream@1.0.5
│ │ │   │ │ └── delayed-stream@1.0.0
│ │ │   │ ├── extend@3.0.0
│ │ │   │ ├── forever-agent@0.6.1
│ │ │   │ ├─┬ form-data@1.0.0-rc3
│ │ │   │ │ └── async@1.4.2
│ │ │   │ ├─┬ har-validator@1.8.0
│ │ │   │ │ ├── bluebird@2.10.1
│ │ │   │ │ ├─┬ chalk@1.1.1
│ │ │   │ │ │ ├── ansi-styles@2.1.0
│ │ │   │ │ │ ├── escape-string-regexp@1.0.3
│ │ │   │ │ │ ├─┬ has-ansi@2.0.0
│ │ │   │ │ │ │ └── ansi-regex@2.0.0
│ │ │   │ │ │ ├─┬ strip-ansi@3.0.0
│ │ │   │ │ │ │ └── ansi-regex@2.0.0
│ │ │   │ │ │ └── supports-color@2.0.0
│ │ │   │ │ ├─┬ commander@2.8.1
│ │ │   │ │ │ └── graceful-readlink@1.0.1
│ │ │   │ │ └─┬ is-my-json-valid@2.12.2
│ │ │   │ │   ├── generate-function@2.0.0
│ │ │   │ │   ├─┬ generate-object-property@1.2.0
│ │ │   │ │   │ └── is-property@1.0.2
│ │ │   │ │   ├── jsonpointer@2.0.0
│ │ │   │ │   └── xtend@4.0.0
│ │ │   │ ├─┬ hawk@3.1.0
│ │ │   │ │ ├── boom@2.9.0
│ │ │   │ │ ├── cryptiles@2.0.5
│ │ │   │ │ ├── hoek@2.16.3
│ │ │   │ │ └── sntp@1.0.9
│ │ │   │ ├─┬ http-signature@0.11.0
│ │ │   │ │ ├── asn1@0.1.11
│ │ │   │ │ ├── assert-plus@0.1.5
│ │ │   │ │ └── ctype@0.5.3
│ │ │   │ ├── isstream@0.1.2
│ │ │   │ ├── json-stringify-safe@5.0.1
│ │ │   │ ├─┬ mime-types@2.1.7
│ │ │   │ │ └── mime-db@1.19.0
│ │ │   │ ├── node-uuid@1.4.3
│ │ │   │ ├── oauth-sign@0.8.0
│ │ │   │ ├── qs@5.1.0
│ │ │   │ ├── stringstream@0.0.4
│ │ │   │ ├── tough-cookie@2.0.0
│ │ │   │ └── tunnel-agent@0.4.1
│ │ │   ├─┬ rimraf@2.4.3
│ │ │   │ └─┬ glob@5.0.14
│ │ │   │   ├─┬ inflight@1.0.4
│ │ │   │   │ └── wrappy@1.0.1
│ │ │   │   ├── inherits@2.0.1
│ │ │   │   ├─┬ minimatch@2.0.10
│ │ │   │   │ └─┬ brace-expansion@1.1.0
│ │ │   │   │   ├── balanced-match@0.2.0
│ │ │   │   │   └── concat-map@0.0.1
│ │ │   │   ├─┬ once@1.3.2
│ │ │   │   │ └── wrappy@1.0.1
│ │ │   │   └── path-is-absolute@1.0.0
│ │ │   ├── semver@5.0.3
│ │ │   ├─┬ tar@2.2.1
│ │ │   │ ├── block-stream@0.0.8
│ │ │   │ ├─┬ fstream@1.0.8
│ │ │   │ │ └── graceful-fs@4.1.2
│ │ │   │ └── inherits@2.0.1
│ │ │   └─┬ tar-pack@2.0.0
│ │ │     ├── debug@0.7.4
│ │ │     ├─┬ fstream@0.1.31
│ │ │     │ ├── graceful-fs@3.0.8
│ │ │     │ └── inherits@2.0.1
│ │ │     ├─┬ fstream-ignore@0.0.7
│ │ │     │ ├── inherits@2.0.1
│ │ │     │ └─┬ minimatch@0.2.14
│ │ │     │   ├── lru-cache@2.7.0
│ │ │     │   └── sigmund@1.0.1
│ │ │     ├── graceful-fs@1.2.3
│ │ │     ├── once@1.1.1
│ │ │     ├─┬ readable-stream@1.0.33
│ │ │     │ ├── core-util-is@1.0.1
│ │ │     │ ├── inherits@2.0.1
│ │ │     │ ├── isarray@0.0.1
│ │ │     │ └── string_decoder@0.10.31
│ │ │     ├── rimraf@2.2.8
│ │ │     ├─┬ tar@0.1.20
│ │ │     │ ├── block-stream@0.0.8
│ │ │     │ └── inherits@2.0.1
│ │ │     └── uid-number@0.0.3
│ │ ├── glob-parent@2.0.0
│ │ ├─┬ is-binary-path@1.0.1
│ │ │ └── binary-extensions@1.3.1
│ │ ├─┬ is-glob@2.0.1
│ │ │ └── is-extglob@1.0.0
│ │ ├─┬ lodash.flatten@3.0.2
│ │ │ ├─┬ lodash._baseflatten@3.1.4
│ │ │ │ ├── lodash.isarguments@3.0.4
│ │ │ │ └── lodash.isarray@3.0.4
│ │ │ └── lodash._isiterateecall@3.0.9
│ │ ├── path-is-absolute@1.0.0
│ │ └─┬ readdirp@2.0.0
│ │   └─┬ readable-stream@2.0.2
│ │     ├── core-util-is@1.0.1
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     ├── process-nextick-args@1.0.3
│ │     ├── string_decoder@0.10.31
│ │     └── util-deprecate@1.0.1
│ ├── colors@1.1.2
│ ├─┬ connect@3.4.0
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├─┬ finalhandler@0.4.0
│ │ │ ├── escape-html@1.0.2
│ │ │ ├─┬ on-finished@2.3.0
│ │ │ │ └── ee-first@1.1.1
│ │ │ └── unpipe@1.0.0
│ │ ├── parseurl@1.3.0
│ │ └── utils-merge@1.0.0
│ ├── core-js@1.2.1
│ ├── di@0.0.1
│ ├─┬ dom-serialize@2.2.0
│ │ ├── custom-event@1.0.0
│ │ ├── ent@2.2.0
│ │ ├── extend@2.0.1
│ │ └── void-elements@1.0.0
│ ├─┬ expand-braces@0.1.1
│ │ ├── array-slice@0.2.3
│ │ ├── array-uniq@1.0.2
│ │ └─┬ braces@0.1.5
│ │   └─┬ expand-range@0.1.1
│ │     ├── is-number@0.1.1
│ │     └── repeat-string@0.2.2
│ ├─┬ glob@5.0.15
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ once@1.3.2
│ │ │ └── wrappy@1.0.1
│ │ └── path-is-absolute@1.0.0
│ ├── graceful-fs@4.1.2
│ ├─┬ http-proxy@1.11.2
│ │ ├── eventemitter3@1.1.1
│ │ └── requires-port@0.0.1
│ ├── lodash@3.10.1
│ ├─┬ log4js@0.6.27
│ │ ├── async@0.2.10
│ │ ├─┬ readable-stream@1.0.33
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ ├── semver@4.3.6
│ │ └── underscore@1.8.2
│ ├─┬ memoizee@0.3.9
│ │ ├── d@0.1.1
│ │ ├─┬ es5-ext@0.10.8
│ │ │ ├── es6-iterator@2.0.0
│ │ │ └── es6-symbol@3.0.0
│ │ ├─┬ es6-weak-map@0.1.4
│ │ │ ├── es6-iterator@0.1.3
│ │ │ └── es6-symbol@2.0.1
│ │ ├── event-emitter@0.3.4
│ │ ├── lru-queue@0.1.0
│ │ ├── next-tick@0.2.2
│ │ └── timers-ext@0.1.0
│ ├── mime@1.3.4
│ ├─┬ minimatch@2.0.10
│ │ └─┬ brace-expansion@1.1.1
│ │   ├── balanced-match@0.2.0
│ │   └── concat-map@0.0.1
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ ├── rimraf@2.4.3
│ ├─┬ socket.io@1.3.7
│ │ ├─┬ debug@2.1.0
│ │ │ └── ms@0.6.2
│ │ ├─┬ engine.io@1.5.4
│ │ │ ├── base64id@0.1.0
│ │ │ ├─┬ debug@1.0.3
│ │ │ │ └── ms@0.6.2
│ │ │ ├─┬ engine.io-parser@1.2.2
│ │ │ │ ├── after@0.8.1
│ │ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ │ ├── blob@0.0.4
│ │ │ │ ├─┬ has-binary@0.1.6
│ │ │ │ │ └── isarray@0.0.1
│ │ │ │ └── utf8@2.1.0
│ │ │ └─┬ ws@0.8.0
│ │ │   ├─┬ bufferutil@1.2.1
│ │ │   │ ├── bindings@1.2.1
│ │ │   │ └── nan@2.0.9
│ │ │   ├── options@0.0.6
│ │ │   ├── ultron@1.0.2
│ │ │   └─┬ utf-8-validate@1.2.1
│ │ │     ├── bindings@1.2.1
│ │ │     └── nan@2.0.9
│ │ ├─┬ has-binary-data@0.1.3
│ │ │ └── isarray@0.0.1
│ │ ├─┬ socket.io-adapter@0.3.1
│ │ │ ├─┬ debug@1.0.2
│ │ │ │ └── ms@0.6.2
│ │ │ ├── object-keys@1.0.1
│ │ │ └─┬ socket.io-parser@2.2.2
│ │ │   ├── benchmark@1.0.0
│ │ │   ├── component-emitter@1.1.2
│ │ │   ├── debug@0.7.4
│ │ │   ├── isarray@0.0.1
│ │ │   └── json3@3.2.6
│ │ ├─┬ socket.io-client@1.3.7
│ │ │ ├── backo2@1.0.2
│ │ │ ├── component-bind@1.0.0
│ │ │ ├── component-emitter@1.1.2
│ │ │ ├── debug@0.7.4
│ │ │ ├─┬ engine.io-client@1.5.4
│ │ │ │ ├── component-inherit@0.0.3
│ │ │ │ ├─┬ debug@1.0.4
│ │ │ │ │ └── ms@0.6.2
│ │ │ │ ├─┬ engine.io-parser@1.2.2
│ │ │ │ │ ├── after@0.8.1
│ │ │ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ │ │ ├── blob@0.0.4
│ │ │ │ │ └── utf8@2.1.0
│ │ │ │ ├─┬ has-cors@1.0.3
│ │ │ │ │ └── global@2.0.1
│ │ │ │ ├─┬ parsejson@0.0.1
│ │ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │ │   └── callsite@1.0.0
│ │ │ │ ├─┬ parseqs@0.0.2
│ │ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │ │   └── callsite@1.0.0
│ │ │ │ ├─┬ parseuri@0.0.4
│ │ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │ │   └── callsite@1.0.0
│ │ │ │ ├─┬ ws@0.8.0
│ │ │ │ │ ├─┬ bufferutil@1.2.1
│ │ │ │ │ │ ├── bindings@1.2.1
│ │ │ │ │ │ └── nan@2.0.9
│ │ │ │ │ ├── options@0.0.6
│ │ │ │ │ ├── ultron@1.0.2
│ │ │ │ │ └─┬ utf-8-validate@1.2.1
│ │ │ │ │   ├── bindings@1.2.1
│ │ │ │ │   └── nan@2.0.9
│ │ │ │ └── xmlhttprequest@1.5.0
│ │ │ ├─┬ has-binary@0.1.6
│ │ │ │ └── isarray@0.0.1
│ │ │ ├── indexof@0.0.1
│ │ │ ├── object-component@0.0.3
│ │ │ ├─┬ parseuri@0.0.2
│ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │   └── callsite@1.0.0
│ │ │ └── to-array@0.1.3
│ │ └─┬ socket.io-parser@2.2.4
│ │   ├── benchmark@1.0.0
│ │   ├── component-emitter@1.1.2
│ │   ├── debug@0.7.4
│ │   ├── isarray@0.0.1
│ │   └── json3@3.2.6
│ ├─┬ source-map@0.4.4
│ │ └── amdefine@1.0.0
│ └─┬ useragent@2.1.7
│   └── lru-cache@2.2.4
├─┬ karma-html-reporter@0.2.6
│ ├── lodash@2.2.1
│ └── mu2@0.5.20
├── karma-mocha@0.2.0
├─┬ karma-mp3-reporter@1.0.0
│ └─┬ player@0.5.1
│   ├── async@0.9.2
│   ├── home@0.1.8
│   ├─┬ lame@1.2.3
│   │ ├── bindings@1.2.1
│   │ ├─┬ debug@2.2.0
│   │ │ └── ms@0.7.1
│   │ ├── nan@2.0.9
│   │ └─┬ readable-stream@1.0.33
│   │   ├── core-util-is@1.0.1
│   │   ├── inherits@2.0.1
│   │   ├── isarray@0.0.1
│   │   └── string_decoder@0.10.31
│   ├── pool_stream@0.0.2
│   ├─┬ speaker@0.2.6
│   │ ├── bindings@1.2.1
│   │ ├─┬ debug@2.2.0
│   │ │ └── ms@0.7.1
│   │ ├── nan@2.0.9
│   │ └─┬ readable-stream@1.0.33
│   │   ├── core-util-is@1.0.1
│   │   ├── inherits@2.0.1
│   │   ├── isarray@0.0.1
│   │   └── string_decoder@0.10.31
│   └── underscore@1.6.0
├─┬ mocha@2.3.3
│ ├── commander@2.3.0
│ ├─┬ debug@2.0.0
│ │ └── ms@0.6.2
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.7.0
│ │   └── sigmund@1.0.1
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ └── supports-color@1.2.0
├── requirejs@2.1.20
└─┬ sinon@1.17.1
  ├── formatio@1.1.1
  ├── lolex@1.3.2
  ├── samsam@1.1.2
  └─┬ util@0.10.3
    └── inherits@2.0.1

**Comment by x2es** [comment]
Hello!

I have upgraded boilerplate to fix this issue. See pull-request #7 Merged into master.
I have disabled `karma-html-reporter` and `karma-mp3-reporter` because of issues with it.
(html-reporter issue: https://github.com/karma-runner/karma/issues/1454)

RequireJS looks a bit outdated in perspective of ES6/7. I recommend to checkout babel+webpack/browserefy. ReactJS community have a lot of sample code/boilerplates for ES6/7.

**Comment by syam-prasad** [comment]
Thanks lot for the response !

Sure I will try it and let you know.

Syam
